import type { Metadata } from 'next';
import './globals.css';
import { Inter } from 'next/font/google';
import { Providers } from 'components/providers';
import { Toaster } from 'react-hot-toast';
import { Toaster as Toast1 } from '@/components/ui/sonner';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <body>
        <Toast1 richColors position="top-right" />
        <Toaster />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
